CREATE TABLE IF NOT EXISTS cities (
  id integer,
  name character varying(100),
  created_at timestamp with time zone,
  description text,
  population integer,
  area integer,
  mayor_name character varying(255),
  mayor_party character varying(100),
  website character varying(255),
  phone character varying(50),
  email character varying(255),
  social_media character varying(255),
  problem_solving_rate integer
);

INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('4', 'OSMANİYE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('5', 'KOCAELİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('6', 'GAZİANTEP', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '33');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('7', 'HATAY', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('8', 'KAYSERİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '50');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('9', 'GÜMÜŞHANE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('10', 'SAKARYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('11', 'BURSA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('12', 'BAYBURT', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('13', 'ÇANAKKALE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('14', 'SİNOP', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('15', 'BARTIN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('16', 'MAĞUSA (KIBRIS)', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('17', 'MERSİN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('18', 'NİĞDE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '100');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('19', 'KONYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('20', 'TOKAT', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('21', 'ADIYAMAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('22', 'ANKARA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('23', 'YOZGAT', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '100');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('24', 'ORDU', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('25', 'RİZE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('26', 'ADANA', '2025-04-10 00:23:01.107079+00', 'Adana, Akdeniz bolgesinde yer alan, tarihi ve kulturel zenginlikleri olan bir ilimizdir.', '2201672', '14030', 'Zeydan Karalar', 'CHP', 'https://www.adana.bel.tr', '444 0 001', 'info@adana.bel.tr', '@adana', '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('85', 'test', '2025-04-11 13:00:09.483254+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('1', 'BURDUR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('2', 'ESKİŞEHİR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '33');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('3', 'ÇANKIRI', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('57', 'AFYONKARAHİSAR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '100');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('58', 'ARTVİN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('59', 'AĞRI', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('60', 'YALOVA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('61', 'NEVŞEHİR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('62', 'TRABZON', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('63', 'SİVAS', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('64', 'ANTALYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('65', 'KASTAMONU', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('66', 'MARDİN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('67', 'KAHRAMANMARAŞ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('68', 'ERZURUM', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('69', 'ARDAHAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('70', 'DÜZCE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('27', 'KIRŞEHİR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('28', 'IĞDIR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('29', 'MANİSA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('30', 'DİYARBAKIR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('31', 'UŞAK', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('32', 'LEFKOŞE (KIBRIS)', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('33', 'AMASYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('34', 'ERZİNCAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '75');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('35', 'ISPARTA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('36', 'GİRNE (KIBRIS)', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('37', 'ELAZIĞ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('38', 'KARABÜK', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('39', 'HAKKARİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('40', 'KARS', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('41', 'ZONGULDAK', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('42', 'AKSARAY', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('43', 'MALATYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('44', 'BALIKESİR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('45', 'DENİZLİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('46', 'MUŞ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('47', 'ŞIRNAK', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('48', 'MUĞLA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('49', 'TEKİRDAĞ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('50', 'KIRKLARELİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('51', 'SİİRT', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('52', 'GİRESUN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('53', 'ŞANLIURFA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('54', 'AYDIN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('55', 'BATMAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('56', 'BİTLİS', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('71', 'SAMSUN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('72', 'ÇORUM', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('73', 'VAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('74', 'BOLU', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('75', 'KÜTAHYA', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('76', 'BİLECİK', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('77', 'İSTANBUL', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('78', 'KİLİS', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('79', 'TUNCELİ', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('80', 'BİNGÖL', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('81', 'EDİRNE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('82', 'KIRIKKALE', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('83', 'KARAMAN', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
INSERT INTO cities (id, name, created_at, description, population, area, mayor_name, mayor_party, website, phone, email, social_media, problem_solving_rate) VALUES ('84', 'İZMİR', '2025-04-10 00:23:01.107079+00', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, '0');
