-- ŞikayetVar Veritabanı Yedeği
-- Tablo: users
-- Tarih: 2025-04-19 21:04:28

START TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
  "id" integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  "name" character varying(100) NOT NULL,
  "email" character varying(255) NOT NULL,
  "password" character varying(255) NOT NULL,
  "profile_image_url" text NULL,
  "bio" text NULL,
  "city_id" integer NULL,
  "district_id" integer NULL,
  "is_verified" boolean NOT NULL DEFAULT false,
  "points" integer NOT NULL DEFAULT 0,
  "post_count" integer NOT NULL DEFAULT 0,
  "comment_count" integer NOT NULL DEFAULT 0,
  "level" character varying(20) NOT NULL DEFAULT 'newUser'::character varying,
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "username" character varying(100) NULL,
  PRIMARY KEY ("id")
);

INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('4', 'Test Kullanıcı', 'test@example.com', 'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae', 'https://i.pravatar.cc/150?img=3', 'Bu bir test kullanıcısı hesabıdır', '26', '1', 't', '100', '0', '0', 'master', '2025-04-10 09:40:47.801913+00', 'test') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('1', 'Admin', 'admin@example.com', '$2b$10$k55g2qPRBM6SCcW8BM3l1OkTEQoiL.Vgab21jzv8x2ZHIV5uC1Pqe', NULL, NULL, NULL, NULL, 't', '15', '0', '2', 'master', '2025-04-09 18:59:03.2124+00', 'admin') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('135', 'Hüseyin Kaplan', 'huseyin.kaplan449@example.com', '565c3761ee159b4eceb2b3349dd79f0906d3890d6c72c0e0a3ae06581098f912.dd6ddc491eb536dbda303815646a4452', 'https://randomuser.me/api/portraits/women/3.jpg', NULL, '35', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'huseyin.kaplan449') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('136', 'Erkan Alp', 'erkan.alp755@example.com', 'f694278f0c4dc50eb2a32278fe413ec4aabed56f22ec431a182dec3407164442.6cda990659316978ce6f462e3cecef6f', 'https://randomuser.me/api/portraits/men/5.jpg', NULL, '6', NULL, 'f', '0', '0', '0', 'contributor', '2025-04-11 20:28:28.663529+00', 'erkan.alp755') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('137', 'Hülya Avcı', 'hulya.avci433@example.com', '3c48f1c477aa0ea333386090bf67dbdca4fb408bbc3a23c03d551ce62df16d96.537cd73a7274deb2d0c801bf36302b2a', 'https://randomuser.me/api/portraits/women/5.jpg', NULL, '6', NULL, 'f', '0', '0', '0', 'expert', '2025-04-11 20:28:28.663529+00', 'hulya.avci433') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('138', 'Esra Öztürk', 'esra.ozturk858@example.com', '2fa24e894b170af0ba74d42bbbd8c80ba218202cfeeb916f45bd9591c3e77108.21096160806c7e0f7393b4ca3313a23e', 'https://randomuser.me/api/portraits/women/2.jpg', NULL, '2', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'esra.ozturk858') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('139', 'Tuğçe Yıldız', 'tugce.yildiz794@example.com', '668252075e309fb5b24dc0fec773862e56bbf7b8a35b132d9b180c6d0f8674cf.9decf2c11dc3e9e3b488fec0ced13abb', 'https://randomuser.me/api/portraits/women/5.jpg', NULL, '2', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'tugce.yildiz794') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('140', 'Yusuf Aktaş', 'yusuf.aktas364@example.com', '537134a878b669d09696ef32337d8b1d8957988b011cbab18a04ed3c4ef28c99.27bb492ca5b77cd4688b12773d92e98f', 'https://randomuser.me/api/portraits/women/1.jpg', NULL, '6', NULL, 'f', '0', '0', '0', 'expert', '2025-04-11 20:28:28.663529+00', 'yusuf.aktas364') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('141', 'Gamze Aktaş', 'gamze.aktas195@example.com', '250d03357214b84e5470e2ebaa53b7963b0451df14d499a111526950a3f84c1c.a3a9c5ae2d6e696e3e50a2179ec082e0', 'https://randomuser.me/api/portraits/men/1.jpg', NULL, '6', NULL, 'f', '0', '0', '0', 'contributor', '2025-04-11 20:28:28.663529+00', 'gamze.aktas195') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('142', 'Elif Yıldırım', 'elif.yildirim80@example.com', '39bbd9cbd947b3534ba0df16734d72f2b28f554e0832b4d52cdef340e035307a.1541fcab77c3d31c9c5c33f390cdf8f8', 'https://randomuser.me/api/portraits/women/1.jpg', NULL, '34', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'elif.yildirim80') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('143', 'Emine Duran', 'emine.duran590@example.com', '3c93395ee446c283cd8c1566d90da04b283dfd24729f5e2405a0e03a6e539617.cb9e786191866dd3742e916924e71d16', 'https://randomuser.me/api/portraits/women/1.jpg', NULL, '2', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'emine.duran590') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('144', 'Ahmet Tekin', 'ahmet.tekin215@example.com', '7a8b584095292d4f43a3044ce22beb8b256944e8dc7fdd3899842537856bd1b7.980bb42e7775ec5adc2e502ef3e45c34', 'https://randomuser.me/api/portraits/women/2.jpg', NULL, '35', NULL, 'f', '0', '0', '0', 'newUser', '2025-04-11 20:28:28.663529+00', 'ahmet.tekin215') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('2', 'Ayşe Kaya', 'ayse@example.com', 'y02IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://ui-avatars.com/api/?name=Ayse+Kaya', NULL, '34', '4', 't', '0', '0', '0', 'newUser', '2023-12-05 14:30:00+00', 'ayse') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";
INSERT INTO users ("id", "name", "email", "password", "profile_image_url", "bio", "city_id", "district_id", "is_verified", "points", "post_count", "comment_count", "level", "created_at", "username") VALUES ('3', 'Mehmet Demir', 'mehmet@example.com', 'y02IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://ui-avatars.com/api/?name=Mehmet+Demir', NULL, '6', '12', 'f', '0', '0', '0', 'newUser', '2023-12-10 09:15:00+00', 'mehmet') ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "password" = EXCLUDED."password", "profile_image_url" = EXCLUDED."profile_image_url", "bio" = EXCLUDED."bio", "city_id" = EXCLUDED."city_id", "district_id" = EXCLUDED."district_id", "is_verified" = EXCLUDED."is_verified", "points" = EXCLUDED."points", "post_count" = EXCLUDED."post_count", "comment_count" = EXCLUDED."comment_count", "level" = EXCLUDED."level", "created_at" = EXCLUDED."created_at", "username" = EXCLUDED."username";

COMMIT;
