-- ŞikayetVar Veritabanı Yedeği
-- Tablo: user_likes
-- Tarih: 2025-04-19 21:04:28

START TRANSACTION;

CREATE TABLE IF NOT EXISTS user_likes (
  "id" integer NOT NULL DEFAULT nextval('user_likes_id_seq'::regclass),
  "user_id" integer NOT NULL,
  "post_id" integer NULL,
  "comment_id" integer NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('52', '142', '81', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('53', '135', '83', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('54', '141', '83', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('55', '139', '82', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('57', '138', '82', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('58', '135', '86', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('59', '136', '88', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('60', '144', '84', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('61', '137', '84', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('62', '141', '87', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('63', '135', '88', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('64', '140', '88', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('65', '140', '81', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('66', '135', '79', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('67', '136', '82', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('68', '142', '83', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('69', '144', '82', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('70', '142', '85', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('71', '140', '83', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('73', '138', '79', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('74', '144', '81', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('75', '137', '88', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('77', '135', '87', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('78', '135', '82', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('79', '139', '84', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('80', '136', '86', NULL, '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('81', '137', NULL, '40', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('82', '143', NULL, '30', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('83', '138', NULL, '36', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('84', '135', NULL, '39', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('85', '140', NULL, '40', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('86', '135', NULL, '25', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('87', '141', NULL, '22', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('88', '139', NULL, '27', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('89', '138', NULL, '32', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('90', '141', NULL, '34', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('91', '140', NULL, '29', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('92', '138', NULL, '37', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('93', '144', NULL, '27', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('94', '140', NULL, '26', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('95', '143', NULL, '35', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('96', '138', NULL, '33', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('97', '140', NULL, '37', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('98', '136', NULL, '39', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('99', '142', NULL, '24', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";
INSERT INTO user_likes ("id", "user_id", "post_id", "comment_id", "created_at") VALUES ('100', '141', NULL, '27', '2025-04-11 20:28:28.663529+00') ON CONFLICT ("id") DO UPDATE SET "user_id" = EXCLUDED."user_id", "post_id" = EXCLUDED."post_id", "comment_id" = EXCLUDED."comment_id", "created_at" = EXCLUDED."created_at";

COMMIT;
